### Login
POST http://localhost:5000/api/login
Content-Type: application/json

{
    username: peter
    passsword: 12345
}

### Register
POST http://localhost:5000/api/register
Content-Type: application/json

{
    username: peter
    passsword: 12345
}